#! /bin/sh
#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/colorblocks/launch.sh &
picom &
bspc config focus_follows_pointer true

bspc monitor -d Ichi Ni San Shi Go

bspc config border_width        5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true

# source the colors.
source "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mpv state=floating